// Flutter imports:
import 'package:flutter/material.dart';

// Package imports:
import 'package:flutter_riverpod/flutter_riverpod.dart';

// Project imports:
import 'package:boorusama/boorus/booru_builder.dart';
import 'package:boorusama/boorus/danbooru/feats/tags/tags.dart';
import 'package:boorusama/boorus/providers.dart';
import 'package:boorusama/flutter.dart';
import 'package:boorusama/foundation/platform.dart';
import 'package:boorusama/foundation/theme/theme.dart';
import 'package:boorusama/string.dart';
import 'package:boorusama/widgets/widgets.dart';

class TagEditAITagView extends ConsumerStatefulWidget {
  const TagEditAITagView({
    super.key,
    required this.onRemoved,
    required this.onAdded,
    required this.isSelected,
    required this.postId,
  });

  final int postId;
  final void Function(String tag) onRemoved;
  final void Function(String tag) onAdded;
  final bool Function(String tag) isSelected;

  @override
  ConsumerState<ConsumerStatefulWidget> createState() =>
      _TagEditAITagViewState();
}

class _TagEditAITagViewState extends ConsumerState<TagEditAITagView> {
  @override
  Widget build(BuildContext context) {
    final tagAsync = ref.watch(danbooruAITagsProvider(widget.postId));

    return SingleChildScrollView(
      child: Column(
        children: [
          WarningContainer(
            margin: const EdgeInsets.symmetric(
              horizontal: 16,
              vertical: 8,
            ),
            contentBuilder: (context) {
              return Text(
                'The suggested tags are generated by AI, please check them carefully before submitting.',
                style: TextStyle(
                  color: context.colorScheme.onError,
                ),
              );
            },
          ),
          Container(
            padding: const EdgeInsets.symmetric(
              horizontal: 8,
              vertical: 4,
            ),
            child: tagAsync.maybeWhen(
              data: (tags) => Wrap(
                spacing: 4,
                runSpacing: isDesktopPlatform() ? 4 : 0,
                children: tags.map((d) {
                  final tag = d.tag;
                  final colors = context.generateChipColors(
                    ref.getTagColor(context, tag.category.name),
                    ref.watch(settingsProvider),
                  );
                  final selected = widget.isSelected(tag.name);

                  return RawChip(
                    selected: selected,
                    showCheckmark: false,
                    checkmarkColor: colors?.foregroundColor,
                    visualDensity: VisualDensity.compact,
                    selectedColor: colors?.backgroundColor,
                    backgroundColor: selected
                        ? colors?.backgroundColor
                        : context.colorScheme.secondaryContainer,
                    side: selected
                        ? colors != null
                            ? BorderSide(
                                width: 1,
                                color: colors.borderColor,
                              )
                            : null
                        : null,
                    onSelected: (value) => value
                        ? widget.onAdded(tag.name)
                        : widget.onRemoved(tag.name),
                    label: ConstrainedBox(
                      constraints: BoxConstraints(
                        maxWidth: context.screenWidth * 0.8,
                      ),
                      child: RichText(
                        overflow: TextOverflow.ellipsis,
                        text: TextSpan(
                          text: tag.name.replaceUnderscoreWithSpace(),
                          style: TextStyle(
                            color: selected
                                ? colors?.foregroundColor
                                : context.colorScheme.onSecondaryContainer,
                            fontWeight:
                                selected ? FontWeight.w700 : FontWeight.w500,
                          ),
                          children: [
                            TextSpan(
                              text: '  ${d.score}%',
                              style: context.textTheme.bodySmall?.copyWith(
                                fontSize: 11,
                                color: context.themeMode.isLight
                                    ? !selected
                                        ? null
                                        : Colors.white.withOpacity(0.85)
                                    : Colors.grey.withOpacity(0.85),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  );
                }).toList(),
              ),
              orElse: () => const Center(
                child: CircularProgressIndicator.adaptive(),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
