name: lint
description: A Dart package for linting.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  analyzer:
  analyzer_plugin:
  custom_lint_builder:

dev_dependencies:
  lints: ^6.0.0
