name: filename_generator
description: A package that generates filenames for files.
publish_to: none

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  clock: ^1.1.1
  equatable: ^2.0.7
  fpdart: ^1.1.1
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
