include: package:lints/recommended.yaml

analyzer:
  errors:
    unnecessary_lambdas: ignore
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    todo: ignore
    parameter_assignments: error

formatter:
  trailing_commas: preserve