name: kurumi
description: The design system and interaction language for Boorusama.
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

resolution: workspace

dependencies:
  animated_list_plus: ^0.5.2
  anchor_ui: ^0.0.6
  collection: ^1.17.0
  context_menus:
    git:
      url: https://github.com/khoadng/flutter-context-menu.git
      ref: 3e46518ea7823aebae8838754c21353bd2d44189
  dynamic_color: ^2.1.0
  equatable: ^2.0.8
  font_awesome_flutter: ^11.0.0
  flutter:
    sdk: flutter
  material_ui: ^1.2.0
  cupertino_ui: ^1.0.2
  material_symbols_icons: ^4.2785.1
  modal_bottom_sheet: ^3.0.0-pre
  oktoast: ^3.4.0
  path_drawing: ^1.0.1
  scroll_to_index: ^3.0.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
