Map<String, String> getHosts() => {
      'artstation.com': 'https://artstation.com',
      'discordapp.com': 'https://discordapp.com',
      'kym-cdn.com': 'https://knowyourmeme.com',
      'wixmp.com': 'https://deviantart.com',
      'fantia.jp': 'https://fantia.jp',
      'hentai-foundry.com': 'https://hentai-foundry.com',
      'exhentai.org': 'https://e-hentai.org',
      'ngfiles.com': 'https://newgrounds.com',
      'i.pximg.net': 'https://pixiv.net',
      'youtu.be': 'https://youtube.com',
      'tumblr.com': 'https://tumblr.com',
      'biligame.com': 'https://bilibili.com',
      'dlsite.jp': 'https://dlsite.jp',
      'yande.re': 'https://yande.re',
      'blog.livedoor.jp': 'https://blog.livedoor.jp',
      'rule34.xxx': 'https://rule34.xxx',
      'sakura.ne.jp': 'https://sakura.ne.jp',
      'fc2.com': 'https://fc2.com',
    };
