name: boorusama_lint
description: Custom lint rules for the Boorusama project
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  analysis_server_plugin: ^0.3.1
  analyzer: ^8.2.0

dev_dependencies:
  analyzer_testing: ^0.1.3
  test: ^1.25.0
  test_reflective_loader: ^0.2.0
